server:
    port: 8002
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Contratos
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    path: /candidatos
    graphiql:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: microservicios-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  application:
    name: servicio-candidatos
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
